name: Build AppImage release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-appimage:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Detect release tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Checkout OpenBoard
      uses: actions/checkout@v2
      with:
        repository: 'OpenBoard-org/OpenBoard'
        path: 'OpenBoard'
        ref: ${{ github.ref }}
    - name: patch OpenBoard
      run: |
        patch -p1 -i ../patches/0001-Modify-directory-hierarchy-based-on-FHS.patch
      working-directory: 'OpenBoard'
    - name: Checkout OpenBoard-Importer
      uses: actions/checkout@v2
      with:
        repository: 'OpenBoard-org/OpenBoard-Importer'
        path: 'OpenBoard-Importer'
    - name: install Qt 5.15.2
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.15.2
        host: linux
        target: desktop
        modules: all
    - name: Install qtwebkit
      run: |
        cd ${Qt5_Dir}
        wget https://download.qt.io/snapshots/ci/qtwebkit/5.212/latest/qtwebkit/qtwebkit-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z
        7z x qtwebkit-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z
    - name: Install linuxdeploy
      uses: miurahr/install-linuxdeploy-action@v1.5.1
      with:
        plugins: qt appimage
    - name: install dependencies
      run: |
        sudo apt-get -y install libgl1-mesa-dev libfontconfig1 libssl-dev libpoppler-dev libpoppler-cpp-dev libpoppler-private-dev libavcodec-dev libavformat-dev libswscale-dev libpaper-dev  libva-dev libxcb-shm0-dev libasound2-dev libx264-dev libvpx-dev libvorbis-dev  libtheora-dev libmp3lame-dev libsdl1.2-dev libopus-dev  libfdk-aac-dev libass-dev liblzma-dev libbz2-dev
        sudo apt-get -y install libquazip5-dev
        sudo apt-get -y install libxcb-shape0-dev libxcb-xfixes0-dev
        sudo apt-get -y install  libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
    - name: build OpenBoard-Importer
      run: |
        qmake OpenBoardImporter.pro CONFIG+=release PREFIX=/usr -spec linux-g++-64
        env LD_LIBRARY_PATH=${Qt5_Dir}/lib:${LD_LIBRARY_PATH} make -j2
      working-directory: 'OpenBoard-Importer'
    - name: build OpenBoard main
      run: |
        qmake OpenBoard.pro CONFIG+=release PREFIX=/usr -spec linux-g++-64
        make -j2
        lrelease OpenBoard.pro
      working-directory: 'OpenBoard'
    - name: install target files
      run: |
        make INSTALL_ROOT=appdir install
        mkdir -p appdir/usr/bin ; cp build/linux/release/product/OpenBoard appdir/usr/bin/openboard
        mkdir -p appdir/usr/translations ; cp resources/i18n/*.qm appdir/usr/translations/
        cp -r resources/library appdir/usr/
        cp -r resources/etc appdir/usr/
        cp -r resources/linux/openboard-ubz.xml appdir/usr/etc/
        mkdir -p appdir/usr/libexec ; install ../OpenBoard-Importer/OpenBoardImporter appdir/usr/libexec/
        mkdir -p appdir/usr/customizations ; cp -r resources/customizations/fonts appdir/usr/customizations/fonts
        mkdir -p appdir/usr/share/icons/hicolor/256x256/apps ; convert resources/images/OpenBoard.png -resize 256x256 appdir/usr/share/icons/hicolor/256x256/apps/OpenBoard.png
        mkdir -p appdir/usr/share/icons/hicolor/64x64/apps ; cp resources/images/OpenBoard.png appdir/usr/share/icons/hicolor/64x64/apps/OpenBoard.png
        rm -rf appdir/home
      working-directory: 'OpenBoard'
    - name: prepare desktop file
      env:
        APPLICATION_CODE: openboard
        APPLICATION_SHORTCUT: appdir/usr/share/applications/openboard.desktop
        APPLICATION_NAME: OpenBoard
        DESCRIPTION: "OpenBoard, an interactive white board application"
      run: |
        mkdir -p appdir/usr/share/applications/
        echo "[Desktop Entry]" > $APPLICATION_SHORTCUT
        echo "Version=1.0" >> $APPLICATION_SHORTCUT
        echo "Name=${APPLICATION_NAME}" >> $APPLICATION_SHORTCUT
        echo "Comment=$DESCRIPTION" >> $APPLICATION_SHORTCUT
        echo "Exec=$APPLICATION_CODE %f" >> $APPLICATION_SHORTCUT
        echo "Icon=${APPLICATION_NAME}" >> $APPLICATION_SHORTCUT
        echo "StartupNotify=true" >> $APPLICATION_SHORTCUT
        echo "Terminal=false" >> $APPLICATION_SHORTCUT
        echo "Type=Application" >> $APPLICATION_SHORTCUT
        echo "Categories=Education;" >> $APPLICATION_SHORTCUT
      working-directory: 'OpenBoard'
    - name: create AppImage
      run: |
        env LD_LIBRARY_PATH=${Qt5_Dir}/lib QMAKE=${Qt5_Dir}/bin/qmake linuxdeploy-x86_64.AppImage ${STD_OPTS} ${LIBS_FLAG} ${ICON_FLAG} ${DESKTOP} -l ${Qt5_Dir}/lib/libQt5Qml.so.5 -l ${Qt5_Dir}/lib/libQt5Quick.so.5 -l ${Qt5_Dir}/lib/libQt5Sensors.so.5 -l ${Qt5_Dir}/lib/libQt5WebChannel.so.5
      env:
        STD_OPTS: --plugin=qt --output=appimage --appdir=appdir
        LIBS_FLAG: 
        ICON_FLAG: --icon-file=appdir/usr/share/icons/hicolor/256x256/apps/OpenBoard.png
        DESKTOP: --desktop-file=appdir/usr/share/applications/openboard.desktop
        OUTPUT: OpenBoard-${{ steps.vars.outputs.tag }}-x86_64.AppImage
      working-directory: 'OpenBoard'
    - name: Upload asset
      uses: actions/upload-artifact@v2
      with:
        name: release-files
        path: OpenBoard/OpenBoard-${{ steps.vars.outputs.tag }}-x86_64.AppImage


  release:
    name: publish on github release
    runs-on: ubuntu-latest
    needs: [build-appimage]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: release-files
        path: OpenBoard
    - name: Detect release tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: OpenBoard-${{ steps.vars.outputs.tag }}-x86_64.AppImage
        tag: ${{ github.ref }}
        overwrite: true

